import type { AppMode } from './types';

export const MODE_LABELS: Record<AppMode, string> = {
  normal: 'Chill',
  tryhard: 'Lock in',
};

export const PALETTES = {
  chill: {
    lockin: false,
    screen: 'bg-cream',
    header: 'bg-paper border-line',
    brand: 'text-ink',
    card: 'bg-paper border-line',
    inset: 'bg-cream',
    primary: 'bg-forest',
    primaryText: 'text-paper',
    secondary: 'bg-sage',
    secondaryText: 'text-forest',
    ghost: 'bg-transparent border-line',
    ghostText: 'text-ink',
    chipOn: 'bg-forest',
    chipOff: 'bg-paper border-line',
    missionOpen: 'border-forest bg-sage',
    missionDone: 'border-forest bg-paper',
    budget: 'border-forest bg-sage',
    toast: 'bg-forest',
    ink: 'text-ink',
    muted: 'text-muted',
    accent: 'text-forest',
    hex: {
      ink: '#1F1A16',
      muted: '#6F675F',
      accent: '#2F5D50',
      flame: '#C17F4A',
      tabBg: '#FFFcf7',
      tabBorder: '#E7E1D6',
      tabActive: '#2F5D50',
      tabInactive: '#6F675F',
      tabPill: '#D7E4DE',
      screen: '#F4F1EA',
      header: '#FFFcf7',
      card: '#FFFcf7',
      line: '#E7E1D6',
      primary: '#2F5D50',
      onPrimary: '#FFFcf7',
      secondary: '#D7E4DE',
      onSecondary: '#2F5D50',
    },
  },
  lockin: {
    lockin: true,
    screen: 'bg-ember',
    header: 'bg-charcoal border-emberLine',
    brand: 'text-flameSoft',
    card: 'bg-emberCard border-emberLine',
    inset: 'bg-ember',
    primary: 'bg-flame',
    primaryText: 'text-ash',
    secondary: 'bg-emberCard border border-flame',
    secondaryText: 'text-flameSoft',
    ghost: 'bg-transparent border-emberLine',
    ghostText: 'text-ash',
    chipOn: 'bg-flame',
    chipOff: 'bg-emberCard border-emberLine',
    missionOpen: 'border-flame bg-emberCard',
    missionDone: 'border-flameSoft bg-[#3A2418]',
    budget: 'border-flame bg-emberCard',
    toast: 'bg-flame',
    ink: 'text-ash',
    muted: 'text-smoke',
    accent: 'text-flameSoft',
    hex: {
      ink: '#F6EDE6',
      muted: '#D4C4B8',
      accent: '#FFB36A',
      flame: '#E85D04',
      tabBg: '#24120C',
      tabBorder: '#5A3224',
      tabActive: '#FFB36A',
      tabInactive: '#C4A99A',
      tabPill: '#5A3224',
      screen: '#1C100C',
      header: '#24120C',
      card: '#2B1710',
      line: '#5A3224',
      primary: '#E85D04',
      onPrimary: '#FFF7F0',
      secondary: '#3A2418',
      onSecondary: '#FFB36A',
    },
  },
} as const;

export type Palette = (typeof PALETTES)[keyof typeof PALETTES];

export function paletteFor(mode: AppMode | undefined): Palette {
  return mode === 'tryhard' ? PALETTES.lockin : PALETTES.chill;
}
